language: ruby
sudo: false
cache: bundler

before_install:
  - gem update --system

before_script:
  - chmod +x ./bin/setup
  - ./bin/setup
  - LC_ALL=en_US.UTF-8 JEKYLL_ENV=production bundle exec jekyll build
  - LC_ALL=en_US.UTF-8 JEKYLL_ENV=production bundle exec jekyll build

script: LC_ALL=en_US.UTF-8 bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml,/facebook.com/"

branches:
  except:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - LC_ALL=en_US.UTF-8
    - JEKYLL_ENV=production
