# Mandatory settings

blog_theme: light # Or use dark
name: Rahul Jain
url: https://rahulja.in
description: This is the personal blog and profile of Rahul Jain, a full-stack engineer and web enthusiast living in Hyderabad, India.
timezone: Asia/Kolkata
encoding: utf-8

# Optional settings
baseurl: # Set if blog doesn't sit at the root of the domain (format: /blog)
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: rahulja-in # Add your Disqus identifier
ga_analytics: UA-75936371-1 # Add your GA Tracking Id
local_fonts: true # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
social_links:
  facebook: xRahulJain # Add your Facebook handle
  github: xRahul # Add your GitHub handle
  linkedin: xRahulJain # Add your LinkedIn handle
  twitter: xRahulJain # Add your Twitter handle
  googleplus: RahulJain17 # Add your Google Plus handle here
  email: rahul_jain@live.in # Add your Email address
  stackoverflow: 1435626/rahul # Add your stackoverflow id/name
  freecodecamp: xrahul # Add your freecodecamp username
  #bitcoin: 1BmYjgdCkY6P8tmmxjm4f5stDK7vJ6VcQN # Add your Bitcoin wallet ID
  flattr: "https://flattr.com/submit/auto?fid=djeqkn&url=https%3A%2F%2Frahulja.in"


# Process and render draft posts
# show_drafts: false
# Publish posts or collection documents with a future date
# future: false
# Render posts that were marked as unpublished
# unpublished: false
# Produce an index for related posts.
# lsi: true

author:
  name: Rahul Jain
  email: rahul_jain@live.in
  uri: https://rahulja.in/about

# Important settings (change at own risk)

ampdir: amp

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: all


pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/posts/page/:num/'
  # Optional the title format for the paginated pages
  # (supports :title for original page title,
  # :num for pagination page number, :max for total number of pages)
  title: ':title - Page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'
  # Optional, the default tag to use, omit to disable
  #tag: ''
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  #locale: ''
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  #trail:
  #  before: 2
  #  after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  #extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

permalink: posts/:slug

# Important settings
assets:
  digest: false
  source_maps: true
  compression: true
  gzip: true
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {jpegoptim: {strip: all}}}
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
  sources:
    - node_modules
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: https://rahulja.in

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
  my_projects:
    output: true
    permalink: /project/:slug/

# using defaults- https://jekyllrb.com/docs/configuration/
defaults:
  -
    scope:
      path: ""
      type: my_projects
    values:
      layout: articles_by_project
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  # sitemap defaults from robots.txt
  -
    scope:
      path: "tag/"
    values:
      sitemap: false
  -
    scope:
      path: "project/*"
    values:
      sitemap: false
  -
    scope:
      path: "tags"
    values:
      sitemap: false
  -
    scope:
      path: "files/*.pdf"
    values:
      sitemap: false

exclude:
  - .bundle/
  - .jekyll-cache/
  - bin/*
  - .gitignore
  - .ruby-version
  - .travis.yml
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - README.md
  - yarn-error.log
  - yarn.lock
  - node_modules/
  - vendor/

plugins:
  - amp-jekyll
  - jemoji
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at

#Custom variables
attribution:
  template:
    project_url: https://github.com/nielsenramon/chalk
    creator_url: http://nielsenramon.com

